"""add conversation model and update messages

Revision ID: 704313a1a262
Revises: 09da8a257e0a
Create Date: 2026-04-28 12:00:44.909290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704313a1a262'
down_revision: Union[str, Sequence[str], None] = '09da8a257e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_one_id', sa.Integer(), nullable=False),
    sa.Column('participant_two_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_one_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_two_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('conversation_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'is_read')
    op.drop_column('messages', 'conversation_id')
    op.drop_table('conversations')
    # ### end Alembic commands ###
