"""cascade_delete_on_post_fks

Revision ID: 79a1ce53c13f
Revises: 26a31815db14
Create Date: 2026-03-18 14:50:57.595953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a1ce53c13f'
down_revision: Union[str, Sequence[str], None] = '26a31815db14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comments_post_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_tags_post_id_fkey'), 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_visible_races_post_id_fkey'), 'post_visible_races', type_='foreignkey')
    op.create_foreign_key(None, 'post_visible_races', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'post_visible_races', type_='foreignkey')
    op.create_foreign_key(op.f('post_visible_races_post_id_fkey'), 'post_visible_races', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('post_tags_post_id_fkey'), 'post_tags', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_post_id_fkey'), 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
