"""add_last_message_at_to_conversations

Revision ID: c51e786f0552
Revises: 704313a1a262
Create Date: 2026-05-11 15:41:01.726435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51e786f0552'
down_revision: Union[str, Sequence[str], None] = '704313a1a262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'last_message_at')
    # ### end Alembic commands ###
